export enum LowLevelFeature {
  AVG_LOUDNESS = 'lowlevel.average_loudness',
  DYN_COMPLEXITY = 'lowlevel.dynamic_complexity',
  REPLAY_GAIN = 'metadata.audio_properties.replay_gain',
  TAGS = 'metadata.tags',
  BEATS_COUNT = 'rhythm.beats_count',
  LOUDNESS_MEAN = 'rhythm.beats_loudness.mean',
  BPM = 'rhythm.bpm',
  FIRST_PEAK_BPM_MEAN = 'rhythm.bpm_histogram_first_peak_bpm.mean',
  SECOND_PEAK_BPM_MEAN = 'rhythm.bpm_histogram_second_peak_bpm.mean',
  DANCEABILITY = 'rhythm.danceability',
  ONSET_RATE = 'rhythm.onset_rate',
  CHORD_CHANGE_RATE = 'tonal.chords_changes_rate',
  CHORDS_KEY = 'tonal.chords_key',
  CHORDS_SCALE = 'tonal.chords_scale',
  KEY_KEY = 'tonal.key_key',
  KEY_SCALE = 'tonal.key_scale',
  KEY_STRENGTH = 'tonal.key_strength',
  TUNING_TEMPERED_DEV = 'tonal.tuning_equal_tempered_deviation',
  TUNING_FREQ = 'tonal.tuning_frequency',
}
